apiVersion: v1
kind: Service
metadata:
  name: llama-4-scout
  namespace: llmdbench
  labels:
    app: llama-4-scout
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: llama-4-scout
  type: ClusterIP
