kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis-lookup-server
  namespace: aibrix-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: redis-lookup-server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: redis-lookup-server
    spec:
      containers:
        - name: lookup-server
          image: 'redis:latest'
          command:
            - redis-server
          ports:
            - name: redis-port
              containerPort: 6379
              protocol: TCP
          resources:
            limits:
              cpu: '4'
              memory: 10G
            requests:
              cpu: '4'
              memory: 8G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600