apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  name: llama3-8b
  namespace: vllm-prod
spec:
  extensionRef:
    name: llama3-8b-epp
  selector:
    llm-d.ai/inferenceServing: "true"
    llm-d.ai/model: llama3-8b
  targetPortNumber: 8000
