apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-d-results-pvc
  namespace: llm-d-benchmark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: standalone-results-pvc
  namespace: llm-d-benchmark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
