apiVersion: v1
kind: ConfigMap
metadata:
  name: standalone-benchmark-env
  namespace: llm-d-benchmark
data:
  # UPDATE TO MATCH YOUR CLUSTER & DEPLOYMENT
  # Core benchmark configuration
  LLMDBENCH_FMPERF_NAMESPACE: "llm-d-benchmark"
  LLMDBENCH_HARNESS_STACK_TYPE: "vllm-prod"
  LLMDBENCH_HARNESS_ENDPOINT_URL: "https://vllm-service.vllm-namespace.cluster.local.svc"
  LLMDBENCH_HARNESS_STACK_NAME: "standalone-vllm-llama-3b"
  LLMDBENCH_HARNESS_WORKLOAD_FILE: "llmdbench_workload.yaml"
  LLMDBENCH_FMPERF_REPETITION: "1"
  LLMDBENCH_HARNESS_RESULTS_DIR: "/requests"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-d-benchmark-env
  namespace: llm-d-benchmark
data:
  # UPDATE TO MATCH YOUR CLUSTER & DEPLOYMENT
  # Core benchmark configuration
  LLMDBENCH_FMPERF_NAMESPACE: "llm-d-benchmark"
  LLMDBENCH_HARNESS_STACK_TYPE: "llm-d"
  LLMDBENCH_HARNESS_ENDPOINT_URL: "http://llm-d-inference-gateway.llm-d.svc.cluster.local:80"
  LLMDBENCH_HARNESS_STACK_NAME: "llm-d-llama-3b"
  LLMDBENCH_HARNESS_WORKLOAD_FILE: "llmdbench_workload.yaml"
  LLMDBENCH_FMPERF_REPETITION: "1"
  LLMDBENCH_HARNESS_RESULTS_DIR: "/requests"
