apiVersion: apps/v1
kind: Deployment
metadata:
  name: .experiments[0].user-overrides.inference-engine.model[0].label
  labels: .experiments[0].user-overrides.inference-engine.labels
  namespace: .experiments[0].user-overrides.inference-engine.namespace
spec:
  replicas: .experiments[0].user-overrides.inference-engine.replicas.standalone
  selector:
    matchLabels:
      app: .experiments[0].user-overrides.inference-engine.model[0].label
  template:
    metadata:
      labels: .experiments[0].user-overrides.inference-engine.labels
      annotations: .experiments[0].user-overrides.inference-engine.annotations
    spec:
      schedulerName: default-scheduler
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: .experiments[0].user-overrides.inference-engine.accelerators.standalone.key
                operator: In
                values:
                - .experiments[0].user-overrides.inference-engine.accelerators.standalone.value
      containers:
      - name: vllm-standalone-.experiments[0].user-overrides.inference-engine.model[0].label
        image: ".images.user-overrides[]|select(.name==\"vllm\").registry/.images.user-overrides[]|select(.name==\"vllm\").repo/.images.user-overrides[]|select(.name==\"vllm\").image:.images.user-overrides[]|select(.name==\"vllm\").tag"
        imagePullPolicy: Always
        command:
        - /bin/bash
        - "-c"
        args: .experiments[0].user-overrides.inference-engine.command.standalone
        env: .experiments[0].user-overrides.inference-engine.env.standalone
        ports:
        - containerPort: .experiments[0].user-overrides.inference-engine.ports.service
        startupProbe:
          httpGet:
            path: /health
            port: .experiments[0].user-overrides.inference-engine.ports.service
          failureThreshold: 200
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: .experiments[0].user-overrides.inference-engine.ports.service
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: .experiments[0].user-overrides.inference-engine.ports.service
          failureThreshold: 3
          periodSeconds: 5
        resources:
          limits: .experiments[0].user-overrides.inference-engine.resources.prefill
          requests: .experiments[0].user-overrides.inference-engine.resources.prefill
        volumeMounts:
        - name: preprocesses
          mountPath: /setup/preprocess
        - name: cache-volume
          mountPath: /.experiments[0].user-overrides.volumes[0].mount
        - name: .experiments[0].user-overrides.volumes[1].name
          mountPath: .experiments[0].user-overrides.volumes[1].mount
      volumes:
      - name: preprocesses
        configMap:
          name: .prepare.dependencies.files[0]
          defaultMode: 0500
      - name: cache-volume
        persistentVolumeClaim:
          claimName: .experiments[0].user-overrides.volumes[0].name
#          readOnly: true
      - name: .experiments[0].user-overrides.volumes[1].name
        emptyDir:
          medium: .experiments[0].user-overrides.volumes[1].type
          sizeLimit: .experiments[0].user-overrides.volumes[1].size
apiVersion: v1
kind: Service
metadata:
  name: .experiments[0].user-overrides.inference-engine.model[0].name
  namespace: .experiments[0].user-overrides.inference-engine.namespace
  labels: .experiments[0].user-overrides.inference-engine.labels
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    app: .experiments[0].user-overrides.inference-engine.model[0].name
  type: ClusterIP