apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache
  namespace: llmdbench2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  storageClassName: nfs-client-pokprod
