apiVersion: batch/v1
kind: Job
metadata:
  name: benchmark-analysis
  namespace: llm-d-benchmark
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: llm-d-benchmark-analysis
    spec:
      serviceAccountName: benchmark-runner
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: analysis
        # TODO: UPDATE IMAGE
        image: quay.io/sallyom/llm-d-benchmark:quickstart
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        command: ["sh"]
        args: ["-c", "mkdir -p /requests/analysis/plots /requests/analysis/data && python3 /workspace/analysis/analyze_results.py --results-dir /requests && echo 'Analysis complete! Results saved to /requests/analysis/'"]
        env:
        - name: LLMDBENCH_CONTROL_WORK_DIR
          value: "/requests"
        - name: LLMDBENCH_HARNESS_RESULTS_DIR
          value: "/requests"
        # Set matplotlib backend to non-interactive for headless operation
        - name: MPLBACKEND
          value: "Agg"
        volumeMounts:
        - name: results
          mountPath: /requests
      volumes:
      - name: results
        persistentVolumeClaim:
          claimName: benchmark-results-pvc
      restartPolicy: Never
