---
apiVersion: v1
kind: Pod
metadata:
  name: results-retriever
  namespace: llm-d-benchmark
spec:
  serviceAccountName: benchmark-runner
  containers:
  - name: results-retriever
    image: registry.redhat.io/ubi9/ubi:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "Sleeping for 24 hours to allow result access..."
        sleep 86400
    volumeMounts:
    - name: results
      mountPath: /requests
      readOnly: true
  volumes:
  - name: results
    persistentVolumeClaim:
      claimName: benchmark-results-pvc
  restartPolicy: Never
