apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"llama-3-70b"},"name":"llama-3-70b","namespace":"e2e-solution"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"llama-3-70b"}},"template":{"metadata":{"labels":{"app":"llama-3-70b"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"nvidia.com/gpu.product","operator":"In","values":["NVIDIA-A100-SXM4-80GB"]}]}]}}},"containers":[{"args":["vllm serve meta-llama/Llama-3.1-70B-Instruct --port 8087 --max-model-len 20000 --disable-log-requests --gpu-memory-utilization 0.95 --tensor-parallel-size 2"],"command":["/bin/sh","-c"],"env":[{"name":"HF_HOME","value":"/root/.cache/huggingface"},{"name":"HUGGING_FACE_HUB_TOKEN","valueFrom":{"secretKeyRef":{"key":"token","name":"hf-token-secret-llama3-70b"}}},{"name":"VLLM_ALLOW_LONG_MAX_MODEL_LEN","value":"1"}],"image":"vllm/vllm-openai:latest","livenessProbe":{"httpGet":{"path":"/health","port":8087},"initialDelaySeconds":1800,"periodSeconds":10},"name":"llama-3-70b","ports":[{"containerPort":8087}],"readinessProbe":{"httpGet":{"path":"/health","port":8087},"initialDelaySeconds":1800,"periodSeconds":5},"resources":{"limits":{"cpu":"10","ephemeral-storage":"220Gi","memory":"20G","nvidia.com/gpu":"2"},"requests":{"cpu":"2","ephemeral-storage":"10Gi","memory":"6G","nvidia.com/gpu":"2"}},"volumeMounts":[{"mountPath":"/root/.cache/huggingface","name":"cache-volume"},{"mountPath":"/dev/shm","name":"shm"}]}],"volumes":[{"name":"cache-volume","persistentVolumeClaim":{"claimName":"llama-70b-cache"}},{"emptyDir":{"medium":"Memory","sizeLimit":"2Gi"},"name":"shm"}]}}}}
  creationTimestamp: "2025-05-01T18:00:25Z"
  generation: 1
  labels:
    app: llama-3-70b
  name: llama-3-70b
  namespace: e2e-solution
  resourceVersion: "20741904"
  uid: 16e2c7ef-2738-4fd6-b8e4-44775fb29a02
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: llama-3-70b
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: llama-3-70b
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A100-SXM4-80GB
      containers:
      - args:
        - vllm serve meta-llama/Llama-3.1-70B-Instruct --port 8087 --max-model-len
          20000 --disable-log-requests --gpu-memory-utilization 0.95 --tensor-parallel-size
          2
        command:
        - /bin/sh
        - -c
        env:
        - name: HF_HOME
          value: /root/.cache/huggingface
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: hf-token-secret-llama3-70b
        - name: VLLM_ALLOW_LONG_MAX_MODEL_LEN
          value: "1"
        image: vllm/vllm-openai:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8087
            scheme: HTTP
          initialDelaySeconds: 1800
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: llama-3-70b
        ports:
        - containerPort: 8087
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8087
            scheme: HTTP
          initialDelaySeconds: 1800
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "10"
            ephemeral-storage: 220Gi
            memory: 20G
            nvidia.com/gpu: "2"
          requests:
            cpu: "2"
            ephemeral-storage: 10Gi
            memory: 6G
            nvidia.com/gpu: "2"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: cache-volume
        - mountPath: /dev/shm
          name: shm
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: llama-70b-cache
      - emptyDir:
          medium: Memory
          sizeLimit: 2Gi
        name: shm
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-01T18:31:11Z"
    lastUpdateTime: "2025-05-01T18:31:11Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-05-01T18:31:11Z"
    lastUpdateTime: "2025-05-01T18:31:11Z"
    message: ReplicaSet "llama-3-70b-65964c47cb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
