#####
# This is an example of how the matrix specification works.
# It is currently out of date.
# To test, use pipelinerun-matrix-subset.yaml instead.
#####
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: experiment-matrix-run
spec:
  taskRunTemplate:
    serviceAccountName: helm-installer
  workspaces:
    - name: data
      persistentVolumeClaim:
        claimName: workspace-pvc
  params:
    - name: targetNamespacePrefix
      # This can be anything.
      value: $(context.pipelineRun.namespace)
    - name: model-id
      value: "Qwen/Qwen3-0.6B"

    # Harness / Workload
    - name: harnessProfile
      value: shared_prefix_synthetic_short.yaml

    # Output Location
    - name: s3-keys
      value: ibm-cos-secret
    - name: s3-bucket
      value: "cloud-object-storage-cos-standard-ere"
    - name: s3-endpoint
      value: "https://s3.us-east.cloud-object-storage.appdomain.cloud"

    # Control
    - name: debug
      value: false

  pipelineSpec:
    workspaces:
      - name: data
    tasks:
      - name: run-experiment
        taskRef:
          name: experiment
        workspaces:
          - name: data
            workspace: data
        params:
          - name: targetNamespacePrefix
            value: $(params.targetNamespacePrefix)
          - name: model-id
            value: $(params.model-id)
          - name: experimentBaseUrl
            value: https://raw.githubusercontent.com/kalantar/llm-d-benchmark/refs/heads/tekton-poc/tekton-poc/examples/inference-scheduling/

          - name: s3-keys
            value: $(params.s3-keys)
          - name: s3-bucket
            value: $(params.s3-bucket)
          - name: s3-endpoint
            value: $(params.s3-endpoint)

          - name: harnessProfile
            value: $(params.harnessProfile)

          - name: debug
            value: "$(params.debug)"
          - name: pipelineUID
            value: "$(context.pipelineRun.uid)"
        matrix:
          params:
            - name: gaiePluginConfig
              value: 
                - "inf-sche-none.yaml"
                - "inf-sche-prefix.yaml"
                - "inf-sche-kv.yaml"
                - "inf-sche-queue.yaml"
            - name: question_len
              value:
                - "100"
                - "300"
                - "1000"
            - name: output_len
              value: 
                - "100"
                - "300"
                - "1000"
