apiVersion: inference.networking.x-k8s.io/v1alpha1
kind: EndpointPickerConfig
plugins:
  - type: single-profile-handler
  - type: prefix-cache-scorer
    parameters:
      hashBlockSize: 64
      maxPrefixBlocksToMatch: 256
      lruCapacityPerServer: 31250
  - type: kv-cache-scorer
  - type: queue-scorer
  - type: max-score-picker
schedulingProfiles:
  - name: default
    plugins:
      - pluginRef: kv-cache-scorer
        weight: 1.0
      - pluginRef: queue-scorer
        weight: 1.0
      - pluginRef: prefix-cache-scorer
        weight: 1.0
      - pluginRef: max-score-picker