apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-3-70b
  labels:
    app: llama-3-70b
  namespace: dynamo-benchmark
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: llama-3-70b
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: llama-3-70b
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A100-SXM4-80GB
      containers:
      - args:
        - vllm serve meta-llama/Llama-3.1-70B-Instruct --port 80 --max-model-len
          20000 --disable-log-requests --gpu-memory-utilization 0.95 --tensor-parallel-size
          2
        command:
        - /bin/sh
        - -c
        env:
        - name: HF_HOME
          value: /root/.cache/huggingface
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: hf-token
        - name: VLLM_ALLOW_LONG_MAX_MODEL_LEN
          value: "1"
        image: quay.io/llm-d/llm-d-dev:0.0.4-amd64
        imagePullPolicy: Always
        name: llama-3-70b
        ports:
        - containerPort: 80
          protocol: TCP
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_BIND_SERVICE"]
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 5
        resources:
          limits:
            cpu: "10"
            ephemeral-storage: "30Gi"
            memory: 200G
            nvidia.com/gpu: "2"
          requests:
            cpu: "2"
            ephemeral-storage: "10Gi"
            memory: 100G
            nvidia.com/gpu: "2"
        volumeMounts:
        - mountPath: /root/.cache/huggingface
          name: cache-volume
        - mountPath: /dev/shm
          name: shm
      volumes:
      - name: cache-volume
        persistentVolumeClaim:
          claimName: model-cache
      - emptyDir:
          medium: Memory
          sizeLimit: 8Gi
        name: shm
