apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This namespace must match the Subject namespaces for the RBAC in rbac.yaml
namespace: llm-d-benchmark

resources:
- sa.yaml
- rbac.yaml
- pvc.yaml
- benchmark-workload-configmap.yaml
- benchmark-env.yaml
