apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: llm-d-benchmark-job-creator
  namespace: llm-d-benchmark
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: llm-d-benchmark-job-creator-binding
  namespace: llm-d-benchmark
subjects:
- kind: ServiceAccount
  name: benchmark-runner
  namespace: llm-d-benchmark
roleRef:
  kind: Role
  name: llm-d-benchmark-job-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: llm-d-benchmark-restricted-scc
  namespace: llm-d-benchmark
subjects:
- kind: ServiceAccount
  name: benchmark-runner
  namespace: llm-d-benchmark
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:restricted
  apiGroup: rbac.authorization.k8s.io
