apiVersion: inference.networking.x-k8s.io/v1alpha1
kind: EndpointPickerConfig
plugins:
- type: single-profile-handler
- type: decode-filter
- type: prefix-cache-scorer
  parameters:
    mode: cache_tracking
    indexerConfig:
      tokenProcessorConfig:
        blockSize: 64                         # must match vLLM block size if not default (16)
        hashSeed: "42"                        # must match PYTHONHASHSEED in vLLM pods
      kvBlockIndexConfig:
        enableMetrics: true                   # enable kv-block index metrics (prometheus)
        metricsLoggingInterval: 60000000000   # log kv-block metrics as well (1m in nanoseconds)
- type: kv-cache-scorer # kv-cache-utilization
- type: queue-scorer
- type: max-score-picker
schedulingProfiles:
- name: default
  plugins:
    - pluginRef: decode-filter
    - pluginRef: prefix-cache-scorer
      weight: 2.0
    - pluginRef: kv-cache-scorer
      weight: 1.0
    - pluginRef: queue-scorer
      weight: 1.0
    - pluginRef: max-score-picker