name: CI - PR Checks

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
     

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        
      - name: Sanity check repo contents
        run: ls -la

      - name: Run markdown link checker
        uses: ./.github/actions/markdown-link-checker
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: "--quiet --retry"  
