name: CI - PR Benchmark Run

on:
  pull_request:
  workflow_dispatch:
    inputs:
      input_dir:
        description: 'Input directory for benchmark results'
        required: false
        default: '/tmp/cicd/analysis'
      output_dir:
        description: 'Output directory name (S3 prefix and artifact name)'
        required: false
        default: ''


jobs:
  run-benchmark:
    name: Inference Sim Benchmark Test
    runs-on: ubuntu-latest
    timeout-minutes: 240

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Display OS used
        run: |
          cat /etc/*os-*
        shell: bash

      - name: Set input and output directory environment variables
        run: |
          DEFAULT_INPUT_DIR=/tmp/cicd/analysis
          INPUT_DIR="${{ github.event.inputs.input_dir }}"
          if [ -z "$INPUT_DIR" ]; then
            INPUT_DIR="$DEFAULT_INPUT_DIR"
          fi
          echo "INPUT_DIR=$INPUT_DIR" >> $GITHUB_ENV

          if [ -z "${{ github.event.inputs.output_dir }}" ]; then
            timestamp=$(date -u +%Y%m%dT%H%M%SZ)
            echo "OUTPUT_DIR=benchmark-results-${timestamp}" >> $GITHUB_ENV
            echo "Using generated output dir: benchmark-results-${timestamp}"
          else
            echo "OUTPUT_DIR=${{ github.event.inputs.output_dir }}" >> $GITHUB_ENV
            echo "Using provided output dir: ${{ github.event.inputs.output_dir }}"
          fi

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1

      # - name: Set up kubeconfig from secret
      #   run: |
      #     mkdir -p ~/.kube
      #     echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config
      #     chmod 600 ~/.kube/config
      #   shell: bash

      - name: Run install_deps.sh
        run: |
          sudo apt-get update
          ./setup/install_deps.sh
        shell: bash

      - name: Populate python deps
        run: |
          echo -e "pandas\ngrip>=4.6.0\nmatplotlib>=3.7.0\nnumpy>=1.22.0\nseaborn>=0.12.0\nkubernetes>=28.0.0" > requirements.txt

      - name: Install python deps
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "LLMDBENCH_HF_TOKEN=hf-token-placeholder" >> $GITHUB_ENV
          echo "LLMDBENCH_VLLM_MODELSERVICE_URI='hf://random/model'" >> $GITHUB_ENV

      - name: E2E target cloud (modelservice, inference-perf)
        run: ./setup/e2e.sh -c ocp_modelservice_inference-sim -t modelservice --deep

      - name: E2E target cloud (modelservice, fmperf)
        run: ./setup/e2e.sh -c ocp_modelservice_inference-sim -t modelservice --deep -l fmperf -w sanity_short-input

      - name: E2E target cloud (modelservice, guidellm)
        run: ./setup/e2e.sh -c ocp_modelservice_inference-sim -t modelservice --deep -l guidellm -w sanity_concurrent.yaml

      - name: E2E target cloud (modelservice, vllm-benchmark)
        run: ./setup/e2e.sh -c ocp_modelservice_inference-sim -t modelservice --deep -l vllm-benchmark